# Generated by Django 6.0.6 on 2026-07-02 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trackeditem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='trackeditem',
            name='last_notified_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='trackeditem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.product'),
        ),
        migrations.AlterField(
            model_name='trackeditem',
            name='target_price',
            field=models.FloatField(),
        ),
        migrations.RemoveField(
            model_name='trackeditem',
            name='created_at',
        ),
    ]
